spring.application.name=pharmacie-benin

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
# IMPORTANT: Utiliser 'update' pour éviter la suppression des données à chaque redémarrage
# 'update' : Met à jour le schéma sans supprimer les données existantes
# 'create-drop' : Recrée le schéma à chaque démarrage (PERTE DE DONNÉES)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.com.pharmacie.benin=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Thymeleaf
spring.thymeleaf.cache=false
